"""empty message

Revision ID: 55f229142641
Revises: 7b66941e08ff
Create Date: 2024-12-29 09:50:21.219670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f229142641'
down_revision = '7b66941e08ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_sitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitter_name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('pet_owner_id', sa.Integer(), nullable=False),
    sa.Column('pet_sitter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owner_id'], ['pet_owners.id'], ),
    sa.ForeignKeyConstraint(['pet_sitter_id'], ['pet_sitters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('_hash_password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pet_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('pet_type', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_owners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('zip_code')
        batch_op.drop_column('pet_type')
        batch_op.drop_column('pet_name')
        batch_op.drop_column('_hash_password')
        batch_op.drop_column('user_name')

    op.drop_table('appointments')
    op.drop_table('pet_sitters')
    # ### end Alembic commands ###
